#!/usr/bin/env python3
"""
Vendors the Music Assistant shared icon set into the iOS app.

https://github.com/music-assistant/shared-icons is the canonical player/device
icon set for every MA client: the server sends one of its ids in
`player.icon`, and every client is expected to draw the same artwork for it.
The repo is not distributed as a package - it asks consumers to vendor a copy
from a tag, which is what this script does.

It writes three things, all generated and none of them hand-editable:

  iosApp/iosApp/Assets.xcassets/PlayerIcons/  one imageset per canonical id
  iosApp/iosApp/Player/PlayerIconCatalog.swift  ids + legacy map as Swift
  iosApp/SharedIcons/                        licence, attribution, sources

The SVGs go straight into the asset catalog: actool renders the set's stroke
geometry, group transforms and `currentColor` correctly, and keeps a vector
representation alongside the 1x/2x/3x bitmaps, so the icons stay sharp at
accessibility text sizes. Template rendering is what lets them take `.tint`
and `.secondary` like the SF Symbols they sit next to.

Re-run against a newer tag when the set moves:

    scripts/sync_shared_icons.py 1.1.0
"""
import json
import shutil
import sys
import tarfile
import tempfile
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ASSETS_DIR = REPO / "iosApp/iosApp/Assets.xcassets/PlayerIcons"
CATALOG_SWIFT = REPO / "iosApp/iosApp/Player/PlayerIconCatalog.swift"
VENDOR_DIR = REPO / "iosApp/SharedIcons"

TARBALL = "https://codeload.github.com/music-assistant/shared-icons/tar.gz/refs/tags/{tag}"

# Copied verbatim out of the upstream checkout so the licence terms and the
# exact id list ship next to the artwork rather than only in this script.
VENDORED_FILES = ["LICENSE", "ATTRIBUTION.md", "manifest.json", "meta.json"]


def download(tag: str, into: Path) -> Path:
    """Unpacks the tagged source tree and returns its root."""
    archive = into / "shared-icons.tar.gz"
    urllib.request.urlretrieve(TARBALL.format(tag=tag), archive)
    with tarfile.open(archive) as tar:
        tar.extractall(into)
    return next(p for p in into.iterdir() if p.is_dir())


def write_imagesets(source: Path, ids: list[str]) -> None:
    # Rebuilt from scratch rather than merged: ids are never removed upstream,
    # but a local edit or a half-finished sync would otherwise survive forever.
    if ASSETS_DIR.exists():
        shutil.rmtree(ASSETS_DIR)
    ASSETS_DIR.mkdir(parents=True)

    # Namespaced, so the ids (`speaker`, `home`, `music`) can be as generic as
    # upstream likes without colliding with the app's own asset names.
    write_json(
        ASSETS_DIR / "Contents.json",
        {"info": {"author": "xcode", "version": 1}, "properties": {"provides-namespace": True}},
    )

    for icon_id in ids:
        svg = source / "icons" / f"{icon_id}.svg"
        if not svg.exists():
            sys.exit(f"manifest lists '{icon_id}' but icons/{icon_id}.svg is missing")
        imageset = ASSETS_DIR / f"{icon_id}.imageset"
        imageset.mkdir()
        shutil.copy2(svg, imageset / svg.name)
        write_json(
            imageset / "Contents.json",
            {
                "images": [{"filename": svg.name, "idiom": "universal"}],
                "info": {"author": "xcode", "version": 1},
                "properties": {
                    "preserves-vector-representation": True,
                    "template-rendering-intent": "template",
                },
            },
        )


def write_catalog_swift(tag: str, manifest: dict, legacy: dict) -> None:
    """The id list and the legacy map, as Swift rather than a parsed resource.

    Both are pure data that only ever changes when this script runs, so there
    is nothing to gain from decoding JSON at launch - and a `Set` literal the
    compiler has already built is what `PlayerIcon` looks up on every row.
    """
    ids = "\n".join(f'        "{i}",' for i in manifest["icons"])
    pairs = "\n".join(f'        "{k}": "{v}",' for k, v in sorted(legacy["map"].items()))
    defaults = legacy["defaults"]

    CATALOG_SWIFT.write_text(
        f'''// Generated by scripts/sync_shared_icons.py from
// music-assistant/shared-icons {tag} (icon set {manifest["version"]}).
// Do not edit by hand - re-run the script against a newer tag instead.

/// The vendored contents of the shared icon set's `manifest.json` and its
/// pre-1.0 `migration/legacy-map.json`. Read only by ``PlayerIcon``.
enum PlayerIconCatalog {{

    /// Every canonical id in the set. Each one has a matching imageset under
    /// `Assets.xcassets/PlayerIcons`, so membership here means it is drawable.
    /// Upstream guarantees ids are never renamed and never removed.
    static let ids: Set<String> = [
{ids}
    ]

    /// What the set falls back to for an id it does not know.
    static let fallback = "{legacy["fallback"]}"

    /// What a player with no icon of its own gets, by kind.
    static let playerDefault = "{defaults["player"]}"
    static let groupDefault = "{defaults["group"]}"

    /// Pre-1.0 icon names (Material Design Icons, and a few Lucide ones) to
    /// the canonical id that replaced them. Servers that have run the icon
    /// migration never send these; older ones send nothing else.
    static let legacyIds: [String: String] = [
{pairs}
    ]
}}
'''
    )


def write_vendor_dir(tag: str, source: Path, manifest: dict) -> None:
    if VENDOR_DIR.exists():
        shutil.rmtree(VENDOR_DIR)
    VENDOR_DIR.mkdir(parents=True)
    for name in VENDORED_FILES:
        shutil.copy2(source / name, VENDOR_DIR / name)
    shutil.copy2(source / "migration/legacy-map.json", VENDOR_DIR / "legacy-map.json")
    (VENDOR_DIR / "README.md").write_text(
        f"""# Vendored: music-assistant/shared-icons

Tag `{tag}`, icon set version `{manifest["version"]}`, {len(manifest["icons"])} icons.

Upstream: https://github.com/music-assistant/shared-icons
Gallery: https://music-assistant.github.io/shared-icons/

Nothing here is read at runtime. The artwork is compiled into the app from
`iosApp/iosApp/Assets.xcassets/PlayerIcons`, and the id list and legacy map
are generated into `iosApp/iosApp/Player/PlayerIconCatalog.swift`. These files
are the provenance: the licence the artwork ships under, the attribution it
requires, and the exact upstream data the generated Swift was built from.

Refresh everything with:

    scripts/sync_shared_icons.py <tag>
"""
    )


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, indent=2) + "\n")


def main() -> None:
    tag = sys.argv[1] if len(sys.argv) > 1 else "1.0.0"
    with tempfile.TemporaryDirectory() as tmp:
        source = download(tag, Path(tmp))
        manifest = json.loads((source / "manifest.json").read_text())
        legacy = json.loads((source / "migration/legacy-map.json").read_text())

        write_imagesets(source, manifest["icons"])
        write_catalog_swift(tag, manifest, legacy)
        write_vendor_dir(tag, source, manifest)

    print(f"synced {len(manifest['icons'])} icons from shared-icons {tag}")


if __name__ == "__main__":
    main()
